# xray_script
server {
    listen                       unix:/dev/shm/nginx/custom_site.sock ssl backlog=2048 so_keepalive=on proxy_protocol;
    http2                        on;
    set_real_ip_from             unix:;
    real_ip_header               proxy_protocol;

    ssl_certificate              /usr/local/nginx/conf/certs/example.com/fullchain.pem;
    ssl_certificate_key          /usr/local/nginx/conf/certs/example.com/privkey.pem;
    ssl_early_data               on;

    include                      nginxconfig.io/security-proxy.conf;

    access_log                   /var/log/nginx/access.log combined buffer=512k flush=1m;
    error_log                    /var/log/nginx/error.log warn;

    location / {
        proxy_pass                  PROXY_TARGET;
        proxy_redirect              off;
        proxy_set_header Host       $host;
        client_max_body_size        0;
        include                     nginxconfig.io/proxy.conf;
        proxy_set_header Early-Data $ssl_early_data;
    }

    include nginxconfig.io/general.conf;
}
